### ISSUE TITLE
Enhance user experience of evcli psa verify-as command

### ISSUE THREAD

**Issue by yogeshbdeshpande** [veraison/evcli#13]
Current evcli psa verify-as command does not display the Attestation Result individual contents.

As a result, the user of the tool has no clue what happened to the Appraisal of "Evidence".

Proper mechanism is to Decode the Attestation Result and Display accordingly the 
Complete Status, which includes more verbose results as well.

**Comment by thomas-fossati** [comment]
Since attestation results use a normalised format, another approach would be to create a separate CLI that deals with attestation results (verification of the signature, pretty print, etc.) that can be fed by the output from evcli.  This way we'd only have to do the work once instead of repeating the integration for each separate attestation format.

**Comment by yogeshbdeshpande** [comment]
Thinking a bit more about this, I think we can split this into two.
Once the user runs evcli command to exchange with Verifier, the immediate result is a short snapshot which details the high level result with a conclusion of a Success/Failure/Undecided result.

If a user wants to dig deeper into more elaborate Result interpretation one can feed the raw results into another command
that does a bit by bit verbose pretty print of each element.

**Comment by thomas-fossati** [comment]
Unfortunately it is not possible to print the overall appraisal status without a) verifying the signature over the AR, b) parsing the claims-set.

**Comment by yogeshbdeshpande** [comment]
True we need some thinking through how to keep the command simple and meaningful.
Verifying signature, true we need to deal with this properly.

For overall result, I think it is in outer envelope. TrustTier can be deduced without walking into individual claim set ?
What did I missed here?

**Comment by thomas-fossati** [comment]
> For overall result, I think it is in outer envelope. TrustTier can be deduced without walking into individual claim set ? What did I missed here?

Even the overall result lies inside the signed AR (e.g., nested in the JWT's payload).  And for good reasons.

**Comment by yogeshbdeshpande** [comment]
Yes, no question about that. I was referring to individual claim set. We can simplify the Signing aspect also by having some default configuration to begin with

**Comment by thomas-fossati** [comment]
> Yes, no question about that. I was referring to individual claim set.

One still needs to verify the signature and decode the payload before being able to access the overall status claim.  So, at that point you've done basically everything AR-wise.

> We can simplify the Signing aspect also by having some default configuration to begin with

I don't understand this.

**Comment by yogeshbdeshpande** [comment]
> > Yes, no question about that. I was referring to individual claim set.
> 
> One still needs to verify the signature and decode the payload before being able to access the overall status claim. So, at that point you've done basically everything AR-wise.
> 
> > We can simplify the Signing aspect also by having some default configuration to begin with
> 
> I don't understand this.

Basically what I meant was a pre-defined location where the signing key can be kept, prior to executing the command, so that the limited AR can be displayed to the user, rather than the user need to explicitly run another new command to deduce the result.

**Comment by thomas-fossati** [comment]
it's not the signing key, it's a verification key that is needed here, and having it passed as a parameter or read from a default file is orthogonal to which command needs to use it.

**Comment by yogeshbdeshpande** [comment]
Yes, I meant the Verification key,

**Comment by yogeshbdeshpande** [comment]
Closing this as addressed by `arc` tool under https://github.com/veraison/ear repository
