### ISSUE TITLE
CCA support

### ISSUE THREAD

**Issue by thomas-fossati** [veraison/evcli#15]
Add a `cca` sub-command to:

* [x] create a CCA token from a claims-set, platform and realm secret keys
* [x] check the integrity of a CCA token given a matching platform public key
* [x] run a challenge-response session with a Veraison verifier both as RP and Attester
* [x] also add the necessary documentation
* [x] align naming of keys with public CCA documentation

**Comment by yogeshbdeshpande** [comment]
@thomas-fossati I can take the rest of the bits to complete this issue?

**Comment by thomas-fossati** [comment]
> @thomas-fossati I can take the rest of the bits to complete this issue?

please go ahead!

**Comment by yogeshbdeshpande** [comment]
Thank you!

**Comment by yogeshbdeshpande** [comment]
Issue is now complete, marking the last item as complete!
